apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: traceroute
spec:
  version: "v0.0.1"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/replicatedhq/kubectl-traceroute/releases/download/v0.0.1/kubectl-traceroute_0.0.1_linux_amd64-0.0.1.tar.gz
    sha256: "4489859d4be491f210bad20f09889a9a33654b91576401742c29b4f32b68ec5a"
    files:
    - from: kubectl-traceroute
      to: .
    - from: LICENSE
      to: .
    bin: kubectl-traceroute
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/replicatedhq/kubectl-traceroute/releases/download/v0.0.1/kubectl-traceroute_0.0.1_darwin_amd64-0.0.1.tar.gz
    sha256: "d887b9acdbd2fdd3e06f0b3103436c7c9257ce252758cd456233df3c9033d4f0"
    files:
    - from: kubectl-traceroute
      to: .
    - from: LICENSE
      to: .
    bin: kubectl-traceroute
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/replicatedhq/kubectl-traceroute/releases/download/v0.0.1/kubectl-traceroute_0.0.1_windows_amd64-0.0.1.zip
    sha256: "278b8e2d45f4e9a9df20e6bd863eb867668ad7432b248e088f74b9ab41493823"
    files:
    - from: kubectl-traceroute.exe
      to: .
    - from: LICENSE
      to: .
    bin: kubectl-traceroute.exe
  shortDescription: Debugs a non-functioning service in a Kubernetes cluster
  homepage: https://github.com/replicatedhq/kubectl-traceroute
  caveats: |
    Usage:
      $ kubectl kubectl-traceroute <serviceName><:port>

    For additional options:
      $ kubectl kubectl-traceroute --help

  description: |
    This plugin will...